name: konrad
channels:
    - defaults
    - rttools
dependencies:
    - python>=3.8
    - jupyter-book
    - matplotlib>=2.0.0
    - netcdf4>=1.2.7
    - numpy>1.22.0
    - pyarts==2.5.4
    - pytest
    - scipy>=0.19.0
    - sphinx
    - sphinx_rtd_theme
    - typhon>=0.7.0
    - xarray>=0.9.1
    - pip
    - pip:
        - git+https://github.com/atmtools/climt@rrtmg-only#egg=climt
        - sympl>=0.4.0
