name: Test

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.name }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [ubuntu, macos]
        python-version: [3.6, 3.7]

        include:
          - name: ubuntu
            os: ubuntu-18.04

          - name: macos
            os: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CliMT (MacOS)
        if: matrix.name == 'macos'
        run: |
          brew install gcc@6
          git clone --branch=v.0.16.9 --depth=1 https://github.com/climt/climt
          cd climt
          python -m pip install --upgrade pip
          pip install wheel Cython sympl==0.4.0
          CC=gcc-6 TARGET=HASWELL python setup.py develop --no-deps

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[docs,tests]
          pip list

      - name: Lint with flake8
        if: matrix.name == 'ubuntu' && matrix.python-version == '3.7'
        continue-on-error: true
        run: |
          pip install flake8
          flake8 . --statistics || echo "::error::Check flake8 output for errors"

      - name: Test
        run: |
          pip install pytest
          pytest --pyargs konrad

      - name: Build docs
        continue-on-error: true
        run: |
          cd docs && make html || echo "::error::Documentation build errored."
